services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
      - --write-timeout=600s
    image: semitechnologies/weaviate:${WEAVIATE_VERSION:-latest}
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: on-failure:0
    environment:
      MODEL2VEC_INFERENCE_API: http://model2vec:8080
      DEFAULT_VECTORIZER_MODULE: "text2vec-model2vec"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: text2vec-model2vec,backup-filesystem
      BACKUP_FILESYSTEM_PATH: "/tmp/backups"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      CLUSTER_HOSTNAME: "node1"
      AUTOSCHEMA_ENABLED: "false"
      DISABLE_TELEMETRY: "true"
      DISABLE_LAZY_LOAD_SHARDS: "true"
      GRPC_MAX_MESSAGE_SIZE: 100000000 # 100MB
  model2vec:
    image: cr.weaviate.io/semitechnologies/model2vec-inference:minishlab-potion-base-4M
